//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion_OF
    {
        public int Gestion_OF_ID { get; set; }
        public string Ordre_De_Fabrication { get; set; }
        public string Numero_OF { get; set; }
        public string Article { get; set; }
        public Nullable<int> Quantite_De_Lancement { get; set; }
        public Nullable<int> Qanututé_Realise { get; set; }
        public Nullable<int> Temps_Theorique { get; set; }
        public Nullable<int> Temps_Realise { get; set; }
        public Nullable<System.DateTime> Date_Debut_OF { get; set; }
        public Nullable<System.DateTime> Date_Fin_OF { get; set; }
    }
}
