//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operatrice_tbl
    {
        public int Operatrices_ID { get; set; }
        public string Nom_Prenom { get; set; }
        public string Shift { get; set; }
        public string Matricule { get; set; }
        public string Secteur { get; set; }
        public Nullable<System.TimeSpan> Temps_Debut { get; set; }
        public Nullable<System.TimeSpan> Temps_Fin { get; set; }
        public Nullable<int> Temps_Travail { get; set; }
        public Nullable<int> Nombre_De_Piece_Realise { get; set; }
        public string Image_op { get; set; }
    }
}
