//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning
    {
        public int Event_ID { get; set; }
        public string Article { get; set; }
        public Nullable<int> Qté_Lancement { get; set; }
        public Nullable<System.DateTime> Date_Debut { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public string Description { get; set; }
    }
}
